/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package signin;

import javax.swing.JOptionPane;
import java.util.Base64;
import java.util.Base64.Encoder;

public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Sign_up
     */
    public Signup() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlast_name = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jusername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jusername1 = new javax.swing.JTextField();
        jsign_up = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jfirstname = new javax.swing.JTextField();
        jlastname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlast_name.setBackground(new java.awt.Color(255, 51, 0));
        jlast_name.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 102)));
        jlast_name.setForeground(new java.awt.Color(255, 255, 255));
        jlast_name.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setText("Sign Up");
        jlast_name.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 7, -1, -1));

        jusername.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jusername.setText("Username");
        jlast_name.add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 216, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel2.setText("Password");
        jlast_name.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 327, 147, -1));

        jusername1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jusername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusername1ActionPerformed(evt);
            }
        });
        jlast_name.add(jusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 138, 240, 41));

        jsign_up.setBackground(new java.awt.Color(204, 204, 204));
        jsign_up.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jsign_up.setText("Sign Up");
        jsign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsign_upActionPerformed(evt);
            }
        });
        jlast_name.add(jsign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 140, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("I have an account sign in");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jlast_name.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        jpassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlast_name.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 321, 240, 47));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel5.setText("First Name");
        jlast_name.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 199, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel6.setText("Last Name");
        jlast_name.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 257, -1, -1));

        jfirstname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfirstnameActionPerformed(evt);
            }
        });
        jlast_name.add(jfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 204, 240, 41));

        jlastname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlastnameActionPerformed(evt);
            }
        });
        jlast_name.add(jlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 262, 240, 41));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlast_name, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlast_name, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // signing form show:

        Signin si = new Signin();
        si.setVisible(true);
        si.pack();
        si.setLocationRelativeTo(null);
        this.setVisible(false);
        new Signin().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jsign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsign_upActionPerformed
        // TODO add your handling code here:
        String username = jusername1.getText();
        String first_name = jfirstname.getText();
        String last_name = jlastname.getText();
        String password = jpassword.getText();
        
        if(username.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add A Username");
        }
        if(first_name.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add A First Name");
        }
        if(last_name.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add A Last Name");
        }
        else if(password.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add A Password");
        }

        else{

            Encoder encoder = Base64.getEncoder();
            String pwrd =  encoder.encodeToString(password.getBytes());

            try {
                java.sql.Statement s = Db.mycon().createStatement();
                s.executeUpdate(" INSERT INTO singin (username,firstname,lastname,password)"
                    + "VALUES ('"+username+"','"+first_name+"','"+last_name+"','"+pwrd+"') ");

                JOptionPane.showMessageDialog(rootPane, "Your Account Created");

                this.setVisible(false);
                new Signin().setVisible(true);

            } catch (Exception e) {
                System.out.println(e);
            }
            jusername1.setText("");
            jpassword.setText("");
        }
    }//GEN-LAST:event_jsign_upActionPerformed

    private void jusername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusername1ActionPerformed

    private void jfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfirstnameActionPerformed

    private void jlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlastnameActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jfirstname;
    private javax.swing.JPanel jlast_name;
    private javax.swing.JTextField jlastname;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JButton jsign_up;
    private javax.swing.JLabel jusername;
    private javax.swing.JTextField jusername1;
    // End of variables declaration//GEN-END:variables


    
}
